/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeVerifyRouteImport } from './routes/_home/verify'
import { Route as HomeSustainabilityRouteImport } from './routes/_home/sustainability'
import { Route as HomeOperationsRouteImport } from './routes/_home/operations'
import { Route as HomeInvestorsRouteImport } from './routes/_home/investors'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeCompanyRouteImport } from './routes/_home/company'
import { Route as AuthPortalRouteImport } from './routes/_auth/portal'
import { Route as AdminVaultRouteImport } from './routes/_admin/vault'
import { Route as AdminLogoutRouteImport } from './routes/_admin/logout'
import { Route as AdminDocumentsRouteImport } from './routes/_admin/documents'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminContactsRouteImport } from './routes/_admin/contacts'
import { Route as HomeVerifyIdRouteImport } from './routes/_home/verify.$id'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeVerifyRoute = HomeVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSustainabilityRoute = HomeSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeOperationsRoute = HomeOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeInvestorsRoute = HomeInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCompanyRoute = HomeCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthPortalRoute = AuthPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminVaultRoute = AdminVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HomeVerifyIdRoute = HomeVerifyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomeVerifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/contacts': typeof AdminContactsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/documents': typeof AdminDocumentsRoute
  '/logout': typeof AdminLogoutRoute
  '/vault': typeof AdminVaultRoute
  '/portal': typeof AuthPortalRoute
  '/company': typeof HomeCompanyRoute
  '/contact': typeof HomeContactRoute
  '/investors': typeof HomeInvestorsRoute
  '/operations': typeof HomeOperationsRoute
  '/sustainability': typeof HomeSustainabilityRoute
  '/verify': typeof HomeVerifyRouteWithChildren
  '/verify/$id': typeof HomeVerifyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/contacts': typeof AdminContactsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/documents': typeof AdminDocumentsRoute
  '/logout': typeof AdminLogoutRoute
  '/vault': typeof AdminVaultRoute
  '/portal': typeof AuthPortalRoute
  '/company': typeof HomeCompanyRoute
  '/contact': typeof HomeContactRoute
  '/investors': typeof HomeInvestorsRoute
  '/operations': typeof HomeOperationsRoute
  '/sustainability': typeof HomeSustainabilityRoute
  '/verify': typeof HomeVerifyRouteWithChildren
  '/verify/$id': typeof HomeVerifyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_admin/contacts': typeof AdminContactsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/documents': typeof AdminDocumentsRoute
  '/_admin/logout': typeof AdminLogoutRoute
  '/_admin/vault': typeof AdminVaultRoute
  '/_auth/portal': typeof AuthPortalRoute
  '/_home/company': typeof HomeCompanyRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/investors': typeof HomeInvestorsRoute
  '/_home/operations': typeof HomeOperationsRoute
  '/_home/sustainability': typeof HomeSustainabilityRoute
  '/_home/verify': typeof HomeVerifyRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_home/verify/$id': typeof HomeVerifyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/logout'
    | '/vault'
    | '/portal'
    | '/company'
    | '/contact'
    | '/investors'
    | '/operations'
    | '/sustainability'
    | '/verify'
    | '/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/logout'
    | '/vault'
    | '/portal'
    | '/company'
    | '/contact'
    | '/investors'
    | '/operations'
    | '/sustainability'
    | '/verify'
    | '/verify/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_home'
    | '/_admin/contacts'
    | '/_admin/dashboard'
    | '/_admin/documents'
    | '/_admin/logout'
    | '/_admin/vault'
    | '/_auth/portal'
    | '/_home/company'
    | '/_home/contact'
    | '/_home/investors'
    | '/_home/operations'
    | '/_home/sustainability'
    | '/_home/verify'
    | '/_home/'
    | '/_home/verify/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/verify': {
      id: '/_home/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof HomeVerifyRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/sustainability': {
      id: '/_home/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof HomeSustainabilityRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/operations': {
      id: '/_home/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof HomeOperationsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/investors': {
      id: '/_home/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof HomeInvestorsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/company': {
      id: '/_home/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof HomeCompanyRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/portal': {
      id: '/_auth/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/vault': {
      id: '/_admin/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AdminVaultRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/logout': {
      id: '/_admin/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/documents': {
      id: '/_admin/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/contacts': {
      id: '/_admin/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_home/verify/$id': {
      id: '/_home/verify/$id'
      path: '/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof HomeVerifyIdRouteImport
      parentRoute: typeof HomeVerifyRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminVaultRoute: typeof AdminVaultRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContactsRoute: AdminContactsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminVaultRoute: AdminVaultRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthPortalRoute: typeof AuthPortalRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthPortalRoute: AuthPortalRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeVerifyRouteChildren {
  HomeVerifyIdRoute: typeof HomeVerifyIdRoute
}

const HomeVerifyRouteChildren: HomeVerifyRouteChildren = {
  HomeVerifyIdRoute: HomeVerifyIdRoute,
}

const HomeVerifyRouteWithChildren = HomeVerifyRoute._addFileChildren(
  HomeVerifyRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeCompanyRoute: typeof HomeCompanyRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeInvestorsRoute: typeof HomeInvestorsRoute
  HomeOperationsRoute: typeof HomeOperationsRoute
  HomeSustainabilityRoute: typeof HomeSustainabilityRoute
  HomeVerifyRoute: typeof HomeVerifyRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeCompanyRoute: HomeCompanyRoute,
  HomeContactRoute: HomeContactRoute,
  HomeInvestorsRoute: HomeInvestorsRoute,
  HomeOperationsRoute: HomeOperationsRoute,
  HomeSustainabilityRoute: HomeSustainabilityRoute,
  HomeVerifyRoute: HomeVerifyRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
